version: '3.8'

services:
  spendo-api:
    build: ./Backend/spendo
    container_name: spendo-backend
    ports:
      - "8000:80"
    volumes:
      - ./Backend/spendo/storage:/var/www/html/storage
    env_file: ./Backend/spendo/.env

  spendo-web:
    build: ./Frontend/Spendo
    container_name: spendo-frontend
    ports:
      - "3000:80"
    depends_on:
      - spendo-api