server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # FRONTEND (React)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # BACKEND (Laravel)
    location /api/ {
        try_files $uri $uri/ /index.php?$query_string;
    }
    
    location ~ \.php$ {
        # Importante: Aquí el root debe ser la carpeta public de Laravel
        root /var/www/html/public;

        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        include fastcgi_params;

        # SCRIPT_FILENAME debe apuntar al archivo físico en el contenedor
        fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location ~ /\. {
        deny all;
    }
}