server {
    listen 80;

    # Frontend (React)
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://spendo-api/api/; # Asegúrate que este nombre sea el de tu servicio en docker-compose
        proxy_http_version 1.1;

        # ESTO ES VITAL: Pasar el header de Authorization
        proxy_set_header Authorization $http_authorization;
        proxy_pass_header Authorization;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # Forzar JSON para evitar redirecciones
        proxy_set_header Accept application/json;
    }

    # Manejo de errores
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}